version: '3.7'
services:
  api-server:
    container_name: parking-lot-finder-backend
    build:
      context: backend-module
      dockerfile: Dockerfile
#    build: .
#    image: parking-lot-finder-backend:0.0.1
    environment:
      SPRING_PROFILES_ACTIVE: dev
      ROOT_LOG_LEVEL: DEBUG
      JAVA_TOOL_OPTIONS: -Xms1G -Xmx1G -Djava.security.egd=file:/dev/./urandom
      TZ: Asia/Seoul
    restart: always
    ports:
      - 8080:8080
#    volumes:
#      - './backend-module:/app'
    networks:
      - api-server
      - ui-server

  ui-server:
    container_name: parking-lot-finder-frontend
    build:
      context: frontend-module
      dockerfile: Dockerfile
      args:
        API_BASE_URL: http://localhost:8080/api/v1
    restart: always
    ports:
      - 3000:3000
    volumes:
      - './frontend-module:/app'
      - '/app/node_modules'
    networks:
      - ui-server
    depends_on:
      - api-server

#volumes:
#  db-data:

networks:
  api-server:
  ui-server:
