version: '3.7'
services:
  api-server:
    container_name: parking-lot-finder-backend
    build:
      context: backend-module
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SEOUL-PARKING-LOT-API-AUTH-KEY: ${SEOUL_PARKING_LOT_API_AUTH_KEY}
      JAVA_TOOL_OPTIONS: -Xms1G -Xmx1G -Djava.security.egd=file:/dev/./urandom
      TZ: Asia/Seoul
    restart: always
    ports:
      - 8080:8080
    networks:
      - api-server
      - ui-server

  ui-server:
    container_name: parking-lot-finder-frontend
    build:
      context: frontend-module
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    volumes:
      - './frontend-module:/app'
      - '/app/node_modules'
    networks:
      - ui-server
    depends_on:
      - api-server

networks:
  api-server:
  ui-server:
