DROP TABLE IF EXISTS PARKING_LOT;

CREATE TABLE PARKING_LOT
(
    PARKING_CODE BIGINT NOT NULL,
    PARKING_NAME VARCHAR(255) NOT NULL,
    TEL VARCHAR(255),
    ADDR VARCHAR(255) NOT NULL,
    RATES BIGINT,
    TIME_RATE BIGINT,
    CAPACITY BIGINT DEFAULT 0,
    CUR_PARKING BIGINT DEFAULT 0,
    SYNC_TIME TIMESTAMP,
    WEEKDAY_END_TIME VARCHAR(255),
    WEEKDAY_BEGIN_TIME VARCHAR(255),
    WEEKEND_END_TIME VARCHAR(255),
    WEEKEND_BEGIN_TIME VARCHAR(255),
    PRIMARY KEY (PARKING_CODE)
) DEFAULT CHARSET=utf8;

CREATE INDEX INDEX_PARKING_NAME ON PARKING_LOT (PARKING_NAME)
CREATE INDEX INDEX_ADDR ON PARKING_LOT (ADDR)
CREATE INDEX INDEX_TEL ON PARKING_LOT (TEL)
CREATE INDEX INDEX_RATES ON PARKING_LOT (RATES)
