DROP TABLE IF EXISTS PARKING_LOT;

CREATE TABLE PARKING_LOT
(
    PARKING_CODE BIGINT NOT NULL,
    PARKING_NAME VARCHAR(255) NOT NULL,
    TEL VARCHAR(255),
    ADDR VARCHAR(255) NOT NULL,
    ADD_RATES DOUBLE,
    ADD_TIME_RATE DOUBLE,
    RATES DOUBLE,
    TIME_RATE DOUBLE,
    HOLIDAY_END_TIME VARCHAR(255),
    HOLIDAY_BEGIN_TIME VARCHAR(255),
    HOLIDAY_PAY_YN VARCHAR(255),
    NIGHT_FREE_OPEN_NM VARCHAR(255),
    OPERATION_RULE_NM VARCHAR(255),
    CAPACITY VARCHAR(255) DEFAULT 0,
    PAY_NM VARCHAR(255),
    SATURDAY_PAY_NM VARCHAR(255),
    PARKING_TYPE_NM VARCHAR(255),
    SYNC_TIME TIMESTAMP,
    WEEKDAY_END_TIME VARCHAR(255),
    WEEKDAY_BEGIN_TIME VARCHAR(255),
    WEEKEND_END_TIME VARCHAR(255),
    WEEKEND_BEGIN_TIME VARCHAR(255),
    PRIMARY KEY (PARKING_CODE)
) DEFAULT CHARSET=utf8;

CREATE INDEX INDEX_PARKING_NAME ON PARKING_LOT (PARKING_NAME)
CREATE INDEX INDEX_ADDR ON PARKING_LOT (ADDR)
CREATE INDEX INDEX_TEL ON PARKING_LOT (TEL)
CREATE INDEX INDEX_RATES ON PARKING_LOT (RATES)
